
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/tech_querydsl
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # ???? SQL?? ??? ?? ??
        format_sql: true
        # ??? ????? ??
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        # System.out? ???? ?????? ?? SQL? ??
#        show_sql: true

logging.level:
    # Logging? ?? SQL? ??
    org.hibernate.SQL: debug